export { TabResumen } from "./tab-resumen";
export { TabContactos } from "./tab-contactos";
export { TabInteligencia } from "./tab-inteligencia";
export { TabFinanzas } from "./tab-finanzas";
export { TabAlertas } from "./tab-alertas";
export { TabAcciones } from "./tab-acciones";
export { TabEmails } from "./tab-emails";
export { TabProductos } from "./tab-productos";
export { TabOperaciones } from "./tab-operaciones";
export { TabSalud } from "./tab-salud";
export { TabVentas } from "./tab-ventas";
export { TabCompras } from "./tab-compras";
export type { ResolvedRelationship, RevenueRow } from "./types";
